### ISSUE TITLE
Progress toward Quality Level 1

### ISSUE THREAD

**Issue by Blast545** [ros2/spdlog_vendor#5]
This issue tracks the progression of `rclcpp` to Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/c2ba03bac23b8f313e47820833fad000dbbe058b/rep-2004.rst). 

* [x] Version Policy
    - Follows ROS Core Quality Declaration
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Follows ROS Core
* [x] PRs automatically tested on Jenkins

Documentation
* [x] Per-feature documentation. 
    - Many features described in different places, but I couldn't find a single unified location.
* [x] Per-item documentation in public API. 
    - Doxygen documentation is generated
    - Many API components are undocumented
* [x] Declared set of licenses
* [x] Copyright statement in each source file
* [x] Quality Declaration document

Testing:

* [x] System tests, which cover "features"
   - (Does not apply for vendored packages)
* [x] Tests covering public API
   - (Does not apply for vendored packages)
* [x] Code coverage 
   - (Does not apply for vendored packages)
* [x] Performance tests
   - (Does not apply for vendored packages)
- [x] Linters and Static Analysis:
   -  Must have a code style and enforce it.
   - Must use static analysis tools where applicable:
     - Linters applied to package.xml and CmakeLists.txt files. See [Linters ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters)

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
   - None
* [x] non-ROS dependencies are equivalent level 1
   - spdlog (QL 3)

Platform Support
* [x] Supports all tier 1 platforms

Security

* [x] Vulnerability Disclosure Policy

**Comment by ahcorde** [comment]
Bump QD to level3 and updated QD https://github.com/ros2/spdlog_vendor/pull/14

Awaiting privileges to edit the issue

**Comment by clalancette** [comment]
Since we know updated this to QL 1 in #16, I believe this issue can be closed.  I'm going to go ahead and do that, but feel free to reopen if there is further work to do on this issue.
