### ISSUE TITLE
CMake warning on Windows

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/spdlog_vendor#9]
First appearance in this packaging job https://ci.ros2.org/view/packaging/job/packaging_windows/1700/

```
  Performing configure step for 'spdlog-1.5.0'

  CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.17/Modules/GNUInstallDirs.cmake:225 (message):

    Unable to determine default CMAKE_INSTALL_LIBDIR directory because no

    target architecture is known.  Please enable at least one language before

    including GNUInstallDirs.

  Call Stack (most recent call first):

    CMakeLists.txt:9 (include)
```

**Comment by clalancette** [comment]
OK, yeah, this is a bug in the upstream spdlog_vendor CMakeLists.txt: https://github.com/gabime/spdlog/blob/v1.5.0/CMakeLists.txt#L9 .  It also looks like it has been fixed on HEAD: https://github.com/gabime/spdlog/commit/1b4621962fd6787b0006ca641944aa5e60b570e5 .  We should be able to just take that commit and apply it to our vendored version to quiet this warning down.

**Comment by nuclearsandwich** [comment]
Thank you @clalancette :heart:
